apiVersion: v1
kind: Service
metadata:
  labels:
    app: guestbook-backend
  name: guestbook-backend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: guestbook-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: guestbook-backend
  name: guestbook-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-backend
  template:
    metadata:
      labels:
        app: guestbook-backend
    spec:
      volumes:
      - name: credentials
        secret:
          secretName: guestbook-backend-account
      containers:
      - name: guestbook-backend
        image: gcr.io/qwiklabs-gcp-gcpd-d4427d502c1d/guestbook-service:latest
        volumeMounts:
        - name: credentials 
          mountPath: "/etc/credentials"
          readOnly: true
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: cloud
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/service-account.json
        ports:
        - name: http
          containerPort: 8080
